In [2]:
import numpy as np

In [12]:
# np.random.seed(52)

rng = np.random.default_rng()

N = np.random.randint(low=3, high=7)
L = np.random.randint(low=2, high=5)

print(N, L)

6 4


In [13]:

P = np.zeros((N, L))
for i in range(L):
  # rows = np.arange(0, N-i) 
  random_values = np.random.randint(low=1, high=10, size=N-i)
  P[0:N-i, i] = random_values

print(P)

[[8. 4. 1. 5.]
 [1. 2. 7. 7.]
 [6. 6. 7. 8.]
 [4. 2. 8. 0.]
 [4. 1. 0. 0.]
 [2. 0. 0. 0.]]
