In [1]:
import numpy as np

In [101]:
def generate_positive_definite_matrix(size: int) -> np.ndarray:
    """
    Generate random symmetric positive definite matrix:
    1. Create random matrix A
    2. Compute A^T * A (always positive semi-definite)
    3. Add diagonal dominance to ensure positive definite
    """
    rng = np.random.default_rng(52)
    
    # Create random matrix
    A = rng.random((size, size))
    
    # Make symmetric positive definite
    matrix = A @ A.T  # Ensures positive semi-definite
    
    # Add to diagonal to ensure positive definite
    matrix += size * np.eye(size)
    
    return matrix

In [102]:
mat_size = 3
mat = generate_positive_definite_matrix(3)
# for i in range(mat_size):
#   for j in range(i, mat_size):
#     mat[i, j] = mat[j, i]

print(mat) 
# mat = np.ndarray((2, 2), dtype=np.int64)

def inverse_iteration(A: np.ndarray, tolerance: np.float64 = 1e-8, max_iter: int = 100):
  dim = A.shape[0]

  # initial guess
  x_prev = np.random.rand(dim)

  res = np.matmul(np.matmul(x_prev.T, A), x_prev)
  print(res)
  
  L = np.linalg.cholesky(A, upper=False)
  U = np.linalg.cholesky(A, upper=True)

  print(L)
  print(U)

  for _ in range(1, max_iter):
    nu = x_prev / np.linalg.norm(x_prev, ord=None)

    # x_next = np.linalg.

inverse_iteration(mat)

[[3.97882539 0.82302082 0.38084467]
 [0.82302082 4.24054186 0.24729345]
 [0.38084467 0.24729345 3.21811758]]
4.119261028215597
[[1.99469932 0.         0.        ]
 [0.41260395 2.01749841 0.        ]
 [0.19092836 0.08352703 1.78176519]]
[[1.99469932 0.41260395 0.19092836]
 [0.         2.01749841 0.08352703]
 [0.         0.         1.78176519]]
