In [49]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [50]:
class LowerMatrix:
    def __init__(self, N: int, L: int, matrix=None):
        self.N = N
        self.L = L

        if matrix is not None:
            self.matrix = matrix
        else:
            self.matrix = np.zeros((N, L), dtype=np.float64)
        # self.matrix = np.zeros((N, L), dtype=np.float64)

    def __getitem__(self, indices):
        i, j = indices
        i1 = i
        j1 = j - i + self.L
        if i1 <= self.L:
            j1 -= self.L - i1

        # print("inside:", i1 - 1, j1 - 1)
        return self.matrix[i1 - 1][j1 - 1]

    def __setitem__(self, indices, value):
        i, j = indices
        i1 = i
        j1 = j - i + self.L

        if i1 < self.L:
            j1 -= self.L - i1

        self.matrix[i1 - 1][j1 - 1] = value

    def K0(self, i: int) -> int:
        """Get starting column index for row i"""
        return max(1, i - self.L + 1)

    def KN(self, i: int) -> int:
        """Get ending column index for row i"""
        return min(self.N, i + self.L - 1)


In [51]:
size = 4
rng = np.random.default_rng()
gen_a = rng.random((size, size), dtype=np.float64)

gen_a[0, size - 1] = 0

for i in range(size):
    for j in range(size):
        if i < j:
            gen_a[j, i] = gen_a[i, j]
print("gen_a: \n", gen_a)
print()

a = LowerMatrix(size, size - 1, gen_a)
# a = LowerMatrix(size, size - 1)


def get_B(A):
    b = LowerMatrix(size, size - 1)

    for i in range(1, size + 1):
        for j in range(a.K0(i), i + 1):
            sum = 0

            for k in range(a.K0(i), j):
                sum += b[i, k] * b[j, k] / b[k, k]
            b[i, j] = A[i, j] - sum
    
    return b 
    # print(f"[{i},{j}]: {a[i,j]:0.3f}")

b = get_B(a)
for i in range(1, size+1):
    for j in range(1, size+1):
      print(b[i, j])

gen_a: 
 [[0.603 0.942 0.26  0.   ]
 [0.942 0.874 0.786 0.499]
 [0.26  0.786 0.987 0.806]
 [0.    0.499 0.806 0.385]]

0.6025852981563832
0.0
0.0


IndexError: index 3 is out of bounds for axis 0 with size 3