In [8]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [9]:
class LowerMatrix:
    def __init__(self, N: int, L: int, matrix=None):
        self.N = N
        self.L = L

        if matrix is not None:
            self.matrix = matrix
        else:
            self.matrix = np.zeros((N, L), dtype=np.float64)
        # self.matrix = np.zeros((N, L), dtype=np.float64)

    def __getitem__(self, indices):
        i, j = indices
        i1 = i
        j1 = j - i + self.L
        if i1 <= self.L:
            j1 -= self.L - i1

        # print("inside:", i1 - 1, j1 - 1)
        return self.matrix[i1 - 1][j1 - 1]

    def __setitem__(self, indices, value):
        i, j = indices
        i1 = i
        j1 = j - i + self.L

        if i1 < self.L:
            j1 -= self.L - i1

        self.matrix[i1 - 1][j1 - 1] = value

    def K0(self, i: int) -> int:
        """Get starting column index for row i"""
        return max(1, i - self.L + 1)

    def KN(self, i: int) -> int:
        """Get ending column index for row i"""
        return min(self.N, i + self.L - 1)


In [11]:
size = 4
rng = np.random.default_rng()
gen_a = rng.random((size, size), dtype=np.float64)

gen_a[0, size - 1] = 0

for i in range(size):
    for j in range(size):
        if i < j:
            gen_a[j, i] = gen_a[i, j]
print("gen_a: \n", gen_a)
print()

a = LowerMatrix(size, size - 1, gen_a)
# a = LowerMatrix(size, size - 1)


def get_B(A):
    b = LowerMatrix(size, size - 1)

    for i in range(1, size + 1):
        for j in range(a.K0(i), i + 1):
            sum = 0

            for k in range(a.K0(i), j):
                sum += b[i, k] * b[j, k] / b[k, k]
            b[i, j] = A[i, j] - sum
    
    return b 
    # print(f"[{i},{j}]: {a[i,j]:0.3f}")

b = get_B(a)
# for i in range(1, size+1):
#     for j in range(1, size+1):
#       print(b[i, j])

gen_a: 
 [[0.26  0.126 0.947 0.   ]
 [0.126 0.314 0.797 0.903]
 [0.947 0.797 0.754 0.1  ]
 [0.    0.903 0.1   0.322]]



In [108]:
rng = np.random.default_rng()
sizee= 5
mm = rng.random((sizee,sizee), dtype=np.double)
for i in range(sizee):
  mm[i,i] *= 1**(-10)

# for i in range(5):
#   for j in range(5):
#     if i!=j:
#         mm[i,j] /= 10**(2)

print(mm, np.linalg.cond(mm))

[[0.482 0.039 0.365 0.965 0.353]
 [0.26  0.792 0.211 0.686 0.724]
 [0.276 0.087 0.245 0.523 0.387]
 [0.647 0.583 0.293 0.418 0.735]
 [0.074 0.017 0.012 0.933 0.21 ]] 22.575299204789058
